/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package error.notepadprojj;

import javax.swing.ImageIcon;

/**
 *
 * @author sudha
 */
public class CalculatorFrame extends javax.swing.JFrame {

    /**
     * Creates new form CalculatorFrame
     */
    public CalculatorFrame() {
        initComponents();
        this.setIconImage(new ImageIcon("C:\\Users\\sudha\\Downloads\\calculator_icon_images.png").getImage());
        this.setTitle("Calculator");
    }
    public void enable(){
        textField.setEnabled(true);
        lessBtn.setEnabled(true);
        mulBtn.setEnabled(true);
        cutBtn.setEnabled(true);
        devBtn.setEnabled(true);
        devBtn.setEnabled(true);
        addBtn.setEnabled(true);
        subBtn.setEnabled(true);
        equalBtn.setEnabled(true);
        dotBtn.setEnabled(true);
        zeroBtn.setEnabled(true);
        oneBtn.setEnabled(true);
        twoBtn.setEnabled(true);
        twoBtn.setEnabled(true);
        threeBtn.setEnabled(true);
        fourBtn.setEnabled(true);
        fiveBtn.setEnabled(true);
        sixBtn.setEnabled(true);
        sevenBtn.setEnabled(true);
        eightBtn.setEnabled(true);
        nineBtn.setEnabled(true);
    }
    public void disable(){
        textField.setEnabled(false);
        lessBtn.setEnabled(false);
        mulBtn.setEnabled(false);
        cutBtn.setEnabled(false);
        devBtn.setEnabled(false);
        devBtn.setEnabled(false);
        addBtn.setEnabled(false);
        subBtn.setEnabled(false);
        equalBtn.setEnabled(false);
        dotBtn.setEnabled(false);
        zeroBtn.setEnabled(false);
        oneBtn.setEnabled(false);
        twoBtn.setEnabled(false);
        twoBtn.setEnabled(false);
        threeBtn.setEnabled(false);
        fourBtn.setEnabled(false);
        fiveBtn.setEnabled(false);
        sixBtn.setEnabled(false);
        sevenBtn.setEnabled(false);
        eightBtn.setEnabled(false);
        nineBtn.setEnabled(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textField = new javax.swing.JTextField();
        onBtn = new javax.swing.JRadioButton();
        offBtn = new javax.swing.JRadioButton();
        lessBtn = new javax.swing.JButton();
        mulBtn = new javax.swing.JButton();
        cutBtn = new javax.swing.JButton();
        devBtn = new javax.swing.JButton();
        addBtn = new javax.swing.JButton();
        subBtn = new javax.swing.JButton();
        equalBtn = new javax.swing.JButton();
        nineBtn = new javax.swing.JButton();
        sixBtn = new javax.swing.JButton();
        threeBtn = new javax.swing.JButton();
        eightBtn = new javax.swing.JButton();
        fiveBtn = new javax.swing.JButton();
        twoBtn = new javax.swing.JButton();
        dotBtn = new javax.swing.JButton();
        sevenBtn = new javax.swing.JButton();
        fourBtn = new javax.swing.JButton();
        oneBtn = new javax.swing.JButton();
        zeroBtn = new javax.swing.JButton();
        lbl1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        textField.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        textField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        onBtn.setText("ON");
        onBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onBtnActionPerformed(evt);
            }
        });

        offBtn.setText("OFF");
        offBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                offBtnActionPerformed(evt);
            }
        });

        lessBtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lessBtn.setText("<-");
        lessBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lessBtnMouseClicked(evt);
            }
        });
        lessBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lessBtnActionPerformed(evt);
            }
        });

        mulBtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        mulBtn.setText("*");
        mulBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mulBtnMouseClicked(evt);
            }
        });
        mulBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mulBtnActionPerformed(evt);
            }
        });

        cutBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cutBtn.setText("Cut");
        cutBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cutBtnMouseClicked(evt);
            }
        });

        devBtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        devBtn.setText("/");
        devBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                devBtnMouseClicked(evt);
            }
        });
        devBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                devBtnActionPerformed(evt);
            }
        });

        addBtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        addBtn.setText("+");
        addBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addBtnMouseClicked(evt);
            }
        });
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        subBtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        subBtn.setText("-");
        subBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                subBtnMouseClicked(evt);
            }
        });

        equalBtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        equalBtn.setText("=");
        equalBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                equalBtnMouseClicked(evt);
            }
        });
        equalBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equalBtnActionPerformed(evt);
            }
        });

        nineBtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        nineBtn.setText("9");
        nineBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nineBtnMouseClicked(evt);
            }
        });
        nineBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nineBtnActionPerformed(evt);
            }
        });

        sixBtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        sixBtn.setText("6");
        sixBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sixBtnMouseClicked(evt);
            }
        });
        sixBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sixBtnActionPerformed(evt);
            }
        });

        threeBtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        threeBtn.setText("3");
        threeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                threeBtnMouseClicked(evt);
            }
        });
        threeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threeBtnActionPerformed(evt);
            }
        });

        eightBtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        eightBtn.setText("8");
        eightBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eightBtnMouseClicked(evt);
            }
        });
        eightBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eightBtnActionPerformed(evt);
            }
        });

        fiveBtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        fiveBtn.setText("5");
        fiveBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fiveBtnMouseClicked(evt);
            }
        });
        fiveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiveBtnActionPerformed(evt);
            }
        });

        twoBtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        twoBtn.setText("2");
        twoBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                twoBtnMouseClicked(evt);
            }
        });
        twoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twoBtnActionPerformed(evt);
            }
        });

        dotBtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        dotBtn.setText(".");
        dotBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dotBtnMouseClicked(evt);
            }
        });
        dotBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dotBtnActionPerformed(evt);
            }
        });

        sevenBtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        sevenBtn.setText("7");
        sevenBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sevenBtnMouseClicked(evt);
            }
        });
        sevenBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sevenBtnActionPerformed(evt);
            }
        });

        fourBtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        fourBtn.setText("4");
        fourBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fourBtnMouseClicked(evt);
            }
        });
        fourBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourBtnActionPerformed(evt);
            }
        });

        oneBtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        oneBtn.setText("1");
        oneBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                oneBtnMouseClicked(evt);
            }
        });
        oneBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneBtnActionPerformed(evt);
            }
        });

        zeroBtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        zeroBtn.setText("0");
        zeroBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                zeroBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textField, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(sixBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(zeroBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                                            .addComponent(onBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(fourBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(oneBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addComponent(offBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(dotBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                                                .addComponent(fiveBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(twoBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(threeBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(lessBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)))
                                        .addComponent(cutBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(sevenBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(eightBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(nineBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(equalBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                            .addComponent(addBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(devBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(mulBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(subBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textField, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(onBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(offBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(addBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(eightBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(sevenBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(nineBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fourBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(fiveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(sixBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(mulBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(threeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(twoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(oneBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(devBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(equalBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dotBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(zeroBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lessBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lessBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lessBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lessBtnActionPerformed

    private void onBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onBtnActionPerformed
        // TODO add your handling code here:
        offBtn.setSelected(false);
        enable();
    }//GEN-LAST:event_onBtnActionPerformed

    private void offBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_offBtnActionPerformed
        // TODO add your handling code here:
        onBtn.setSelected(false);
        disable();
    }//GEN-LAST:event_offBtnActionPerformed

    private void mulBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mulBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mulBtnActionPerformed

    private void eightBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eightBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eightBtnActionPerformed

    private void fourBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fourBtnActionPerformed

    private void oneBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oneBtnActionPerformed

    private void twoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twoBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_twoBtnActionPerformed

    private void threeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threeBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_threeBtnActionPerformed

    private void fiveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiveBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fiveBtnActionPerformed

    private void sixBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sixBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sixBtnActionPerformed

    private void sevenBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sevenBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sevenBtnActionPerformed

    private void nineBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nineBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nineBtnActionPerformed

    private void devBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_devBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_devBtnActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addBtnActionPerformed

    private void equalBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equalBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_equalBtnActionPerformed

    private void dotBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dotBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dotBtnActionPerformed

    private void oneBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_oneBtnMouseClicked
        // TODO add your handling code here:
        textField.setText(textField.getText()+"1");
    }//GEN-LAST:event_oneBtnMouseClicked

    private void twoBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_twoBtnMouseClicked
        // TODO add your handling code here:
        textField.setText(textField.getText()+"2");
    }//GEN-LAST:event_twoBtnMouseClicked

    private void threeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_threeBtnMouseClicked
        // TODO add your handling code here:\
        textField.setText(textField.getText()+"3");
    }//GEN-LAST:event_threeBtnMouseClicked

    private void fourBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fourBtnMouseClicked
        // TODO add your handling code here:
        textField.setText(textField.getText()+"4");
    }//GEN-LAST:event_fourBtnMouseClicked

    private void fiveBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fiveBtnMouseClicked
        // TODO add your handling code here:
        textField.setText(textField.getText()+"5");
    }//GEN-LAST:event_fiveBtnMouseClicked

    private void sixBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sixBtnMouseClicked
        // TODO add your handling code here:
        textField.setText(textField.getText()+"6");
    }//GEN-LAST:event_sixBtnMouseClicked

    private void sevenBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sevenBtnMouseClicked
        // TODO add your handling code here:
        textField.setText(textField.getText()+"7");
    }//GEN-LAST:event_sevenBtnMouseClicked

    private void eightBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eightBtnMouseClicked
        // TODO add your handling code here:
        textField.setText(textField.getText()+"8");
    }//GEN-LAST:event_eightBtnMouseClicked

    private void nineBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nineBtnMouseClicked
        // TODO add your handling code here:
        textField.setText(textField.getText()+"9");
    }//GEN-LAST:event_nineBtnMouseClicked

    private void cutBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cutBtnMouseClicked
        // TODO add your handling code here:
        textField.setText("");
        lbl1.setText("");
    }//GEN-LAST:event_cutBtnMouseClicked

    private void addBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addBtnMouseClicked
        // TODO add your handling code here:
        String textNumber = textField.getText();
        if(!textNumber.isBlank())
        {
            num = Double.parseDouble(textNumber);
            operator="+";
            textField.setText("");
            lbl1.setText(num+"+");
        }
    }//GEN-LAST:event_addBtnMouseClicked

    private void subBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_subBtnMouseClicked
        // TODO add your handling code here:
        String textNumber = textField.getText();
        if(!textNumber.isBlank())
        {
            num = Double.parseDouble(textNumber);
            operator="-";
            textField.setText("");
            lbl1.setText(num+"-");
        }
    }//GEN-LAST:event_subBtnMouseClicked

    private void devBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_devBtnMouseClicked
        // TODO add your handling code here:
        String textNumber = textField.getText();
        if(!textNumber.isBlank())
        {
            num = Double.parseDouble(textNumber);
            operator="/";
            textField.setText("");
            lbl1.setText(num+"/");
        }
    }//GEN-LAST:event_devBtnMouseClicked

    private void mulBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mulBtnMouseClicked
        // TODO add your handling code here:
        String textNumber = textField.getText();
        if(!textNumber.isBlank())
        {
            num = Double.parseDouble(textNumber);
            operator="*";
            textField.setText("");
            lbl1.setText(num+"*");
        } 
        
    }//GEN-LAST:event_mulBtnMouseClicked

    private void equalBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_equalBtnMouseClicked
        // TODO add your handling code here:
        String textNumber = textField.getText();
        if(!textNumber.isBlank())
        {
            String value=lbl1.getText();
            lbl1.setText(value + textField.getText());
            switch(operator){
            case "+":
                result = num+Double.parseDouble(textField.getText());
                textField.setText(Double.toString(result));
                break;
            case "-":
                result = num-Double.parseDouble(textField.getText());
                textField.setText(Double.toString(result));
                break;
            case "/":
                result = num/Double.parseDouble(textField.getText());
                textField.setText(Double.toString(result));
                break;
            case "*":
                result = num*Double.parseDouble(textField.getText());
                textField.setText(Double.toString(result));
                break;
            
        }
        }
        
    }//GEN-LAST:event_equalBtnMouseClicked

    private void dotBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dotBtnMouseClicked
        // TODO add your handling code here:
        textField.setText(textField.getText()+".");
    }//GEN-LAST:event_dotBtnMouseClicked

    private void zeroBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_zeroBtnMouseClicked
        // TODO add your handling code here:
        textField.setText(textField.getText()+"0");
    }//GEN-LAST:event_zeroBtnMouseClicked

    private void lessBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lessBtnMouseClicked
        // TODO add your handling code here:
        int length = textField.getText().length();
        int number = textField.getText().length()-1;
        String store; 
        
        if(length>0){
            StringBuilder back = new StringBuilder(textField.getText());
            back.deleteCharAt(number);
            store=back.toString();
            textField.setText(store);
        }
    }//GEN-LAST:event_lessBtnMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        NoteFrame noteFrm = new NoteFrame();
        noteFrm.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    double num,result;
    String operator;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JButton cutBtn;
    private javax.swing.JButton devBtn;
    private javax.swing.JButton dotBtn;
    private javax.swing.JButton eightBtn;
    private javax.swing.JButton equalBtn;
    private javax.swing.JButton fiveBtn;
    private javax.swing.JButton fourBtn;
    private javax.swing.JLabel lbl1;
    private javax.swing.JButton lessBtn;
    private javax.swing.JButton mulBtn;
    private javax.swing.JButton nineBtn;
    private javax.swing.JRadioButton offBtn;
    private javax.swing.JRadioButton onBtn;
    private javax.swing.JButton oneBtn;
    private javax.swing.JButton sevenBtn;
    private javax.swing.JButton sixBtn;
    private javax.swing.JButton subBtn;
    private javax.swing.JTextField textField;
    private javax.swing.JButton threeBtn;
    private javax.swing.JButton twoBtn;
    private javax.swing.JButton zeroBtn;
    // End of variables declaration//GEN-END:variables
}
